name: daily-expence
on:
  push: 
     branches:
           -main
jobs:
    
  create-relese:
     name: “Create-Release”
     runs-on: windows-10
         
     steps:
      - uses: actions/checkouts@v2
    
      - uses: actions/setup-dotnet@v1
        with:
         dotnet-version: 6.0.x
     
      - uses: actions/setup-nod@v1
      - run: |
         npm install
         gulp
      - uses: actions/upload-artifacts@v3
        with:
         name: daily-expence
         path: Releases/
